### ISSUE TITLE
ACF Compatibility

### ISSUE THREAD

**Issue by mnguye08** [mbo2olivier/mukadi-doctrine-crud#1]
Hi @mbo2olivier,
Is it possible to use your bundle with WP ACF plugin?
If yes, how?

Thanks by advance for your feedback.
Kind regards.

**Comment by mbo2olivier** [comment]
@mnguye08 I guess you're talking about mukadi/wordpress-bundle ? if so then I invite you to close this issue and open it on the page of the concerned bundle, and continue this discussion.
Thank you for your interest in this bundle
Kind regards

PS: sorry for my english, i'm not an english speaker

**Comment by mnguye08** [comment]
OK thanks in advance for your help.
Let's continue the discussion on the other bundle.
